### ISSUE TITLE
[Feat] SellerInfoCell, ProductDetailInfoCollectionViewCell 구현

### ISSUE THREAD

**Issue by choiyoubin** [SOPT-all/35-COLLABORATION-iOS-DAANGN#27]
## 🫧 About

- SellerInfoCell 구현
- ProductDetailInfoCollectionViewCell 구현

## 🎧 TO-DO LIST

- [ ] Seller 목업데이터 구성 
- [ ] 서버에서 받아오는 닉네임, 프로필사진, 주소와 더미데이터인 시간, 매너온도, 온도바 구현 
- [ ] 상품 상세 정보에 상품 명, 카테고리, 끌올 시간, 내용, (관심, 조회),  신고하기 버튼 구현

## 💬 기타 사항
-
