### ISSUE TITLE
[Feat] [홈] 상품 목록 API 연결 및 카테고리 목록 API 연결

### ISSUE THREAD

**Issue by jeonguk29** [SOPT-all/35-COLLABORATION-iOS-DAANGN#38]
## 🫧 About

 [홈] 상품 목록 API 연결 및 카테고리 목록 API 연결

## 🎧 TO-DO LIST

- [ ] [홈] 상품 목록 관련 API 연결 작업
- [ ] 카테고리 목록 API 연결
- [ ] 두개를 이어 자연스럽게 동작하도록 작업

## 💬 기타 사항
-
