### ISSUE TITLE
[Fix] 홈화면 스크롤뷰 내 상품 컬렉션뷰 높이가 contentSize만큼 계산되지 않는 문제 해결

### ISSUE THREAD

**Issue by Nya128** [SOPT-all/35-COLLABORATION-iOS-DAANGN#46]
## 🫧 About

- 홈화면에서 fetchProducts() 서버통신 이후, 스크롤뷰 내에 있는 상품 컬렉션뷰 높이가 content size만큼 딱 맞게 계산되지 않아 레이아웃이 부정확해지는 문제를 해결합니다.

## 🎧 TO-DO LIST

- [x] 상품 컬렉션뷰 및 스크롤뷰 contentSize대로 안 나오는 문제 해결
- [x] fetchProducts() 함수를 viewDidLoad, viewWillAppear 두곳에서 모두 호출할 때만 상품 컬렉션뷰가 잘 나타나는 문제 해결
- [ ] 카테고리 필터 삭제하다가 가끔 스크롤 안 되는 문제...

## 💬 기타 사항
-
